name = "spinner"
version = "1.2.0"

description = "Animated progress spinners for your console"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "spinner" }
links = [
    { title = "Website", href = "https://gleam.run" },
    { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_community_ansi = ">= 1.3.0 and < 2.0.0"
glearray = ">= 0.2.0 and < 2.0.0"
repeatedly = ">= 2.1.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 0.28.0 and < 1.0.0"
